language: python

env:
    global:
        # Set defaults to avoid repeating in most cases
        - NUMPY_VERSION=1.10

matrix:
    include:

        # Try all python versions with the latest numpy
        - python: 3.5
          env: CMD='python setup.py test'
        - python: 3.6
          env: CMD='python setup.py test'
        - python: 3.7
          env: CMD='coverage run --source formulas -m py.test'

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

    # UPDATE APT-GET LISTINGS
    - sudo apt-get update

install:

    # CONDA
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - conda install --yes numpy=$NUMPY_VERSION pytest pip yt astropy mpmath

    # COVERAGE DEPENDENCIES
    - pip install coverage coveralls

script:
    - $CMD

after_success:
    - if [[ $CMD == 'coverage run --source formulas -m py.test' ]]; then
          coveralls --rcfile='formulas/tests/coveragerc';
      fi
